[package]
name = "primgen"
version = "0.1.0"
authors = ["stabenau"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-array="*"
typenum="*"
rand = "0.7"

